In [1]:
import numpy as np
import pandas as pd
from utils import read_q_mat, read_a_mat
import scipy.io
import keras
from sim import model_setup, sim_hb


In [2]:
start_date = '1996-01-01'
end_date = '2005-01-01'
q_vu = '/Users/cooper/Desktop/optimal-wat-allocation/Script/MAT_data/q_vuquang.mat'
q_ye = '/Users/cooper/Desktop/optimal-wat-allocation/Script/MAT_data/q_yenbai.mat'
a = '/Users/cooper/Desktop/optimal-wat-allocation/Script/MAT_data/a_hoabinh_K.mat'

qq, sys_params = model_setup(
    ini_date=start_date,
    fin_date=end_date,
    path_a_hoabinh_K=a,
    path_q_vuquang=q_vu,
    path_q_yenbai=q_ye,
)

In [3]:
h, u, r, ht_HN = sim_hb(
    qq=qq,
    h_in=104,
    policy=(89, 1-7, 1.57, 1.5704, 5000),
    sys_param=sys_params
)

103/103 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step


/opt/anaconda3/envs/remSensEnv/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
h

array([104.        , 102.0401349 , 100.08335559, ...,  79.51608443,
        79.51539301,  79.51473799])

In [5]:
u

array([5003.01570677, 5002.96197606, 5002.90832994, ..., 5002.34446759,
       5002.34444863,           nan])

In [6]:
r

array([          nan, 5003.01570677, 5002.96197606, ...,  443.41685536,
        423.92828454,  405.87942746])

In [7]:
ht_HN

array([      nan, 485.90906, 485.76215, ..., 482.15448, 482.25385,
       482.17197], dtype=float32)